/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.24
 * Generated at: 2024-10-02 11:33:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- BEGIN SLIDER -->\r\n");
      out.write("<div class=\"page-slider margin-bottom-35\">\r\n");
      out.write("  <!-- LayerSlider start -->\r\n");
      out.write("  <div id=\"layerslider\" style=\"width: 100%; height: 494px; margin: 0 auto;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- slide one start -->\r\n");
      out.write("    <div class=\"ls-slide ls-slide1\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 24,25,27,28;\">\r\n");
      out.write("\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide1/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"ls-l ls-title\" style=\"top: 96px; left: 35%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("        fade: true; \r\n");
      out.write("        fadeout: true; \r\n");
      out.write("        durationin: 750; \r\n");
      out.write("        durationout: 750; \r\n");
      out.write("        easingin: easeOutQuint; \r\n");
      out.write("        rotatein: 90; \r\n");
      out.write("        rotateout: -90; \r\n");
      out.write("        scalein: .5; \r\n");
      out.write("        scaleout: .5; \r\n");
      out.write("        showuntil: 4000;\r\n");
      out.write("      \">Tones of <strong>shop UI features</strong> designed</div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"ls-l ls-mini-text\" style=\"top: 338px; left: 35%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true; \r\n");
      out.write("      durationout: 750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      delayin: 300; \r\n");
      out.write("      showuntil: 4000;\r\n");
      out.write("      \">Lorem ipsum dolor sit amet  constectetuer diam<br > adipiscing elit euismod ut laoreet dolore.\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- slide one end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- slide two start -->\r\n");
      out.write("    <div class=\"ls-slide ls-slide2\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 110,111,112,113;\">\r\n");
      out.write("\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide2/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"ls-l ls-title\" style=\"top: 40%; left: 21%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true;  \r\n");
      out.write("      durationin: 750; durationout: 109750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      easingout: easeInOutQuint; \r\n");
      out.write("      delayin: 0; \r\n");
      out.write("      delayout: 0; \r\n");
      out.write("      rotatein: 90; \r\n");
      out.write("      rotateout: -90; \r\n");
      out.write("      scalein: .5; \r\n");
      out.write("      scaleout: .5; \r\n");
      out.write("      showuntil: 4000;\r\n");
      out.write("      \"><strong>Unlimted</strong> Layout Options <em>Fully Responsive</em>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"ls-l ls-price\" style=\"top: 50%; left: 45%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true;  \r\n");
      out.write("      durationout: 109750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      delayin: 300; \r\n");
      out.write("      scalein: .8; \r\n");
      out.write("      scaleout: .8; \r\n");
      out.write("      showuntil: 4000;\"><b>from</b> <strong><span>$</span>25</strong>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <a href=\"#\" class=\"ls-l ls-more\" style=\"top: 72%; left: 21%; display: inline-block; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true; \r\n");
      out.write("      durationin: 750; \r\n");
      out.write("      durationout: 750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      easingout: easeInOutQuint; \r\n");
      out.write("      delayin: 0; \r\n");
      out.write("      delayout: 0; \r\n");
      out.write("      rotatein: 90; \r\n");
      out.write("      rotateout: -90; \r\n");
      out.write("      scalein: .5; \r\n");
      out.write("      scaleout: .5; \r\n");
      out.write("      showuntil: 4000;\">See More Details\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- slide two end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- slide three start -->\r\n");
      out.write("    <div class=\"ls-slide ls-slide3\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 92,93,105;\">\r\n");
      out.write("\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide3/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"ls-l ls-title\" style=\"top: 83px; left: 33%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true; \r\n");
      out.write("      durationin: 750; \r\n");
      out.write("      durationout: 750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      rotatein: 90; \r\n");
      out.write("      rotateout: -90; \r\n");
      out.write("      scalein: .5; \r\n");
      out.write("      scaleout: .5; \r\n");
      out.write("      showuntil: 4000;\r\n");
      out.write("      \">Full Admin &amp; Frontend <strong>eCommerce UI</strong> Is Ready For Your Project\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"ls-l\" style=\"top: 333px; left: 33%; white-space: nowrap; font-size: 20px; font: 20px 'Open Sans Light', sans-serif;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true; \r\n");
      out.write("      durationout: 750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      delayin: 300; \r\n");
      out.write("      scalein: .8; \r\n");
      out.write("      scaleout: .8; \r\n");
      out.write("      showuntil: 4000;\r\n");
      out.write("      \">\r\n");
      out.write("        <a href=\"#\" class=\"ls-buy\">\r\n");
      out.write("          Buy It Now!\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"ls-price\">\r\n");
      out.write("          <span>All these for only:</span>\r\n");
      out.write("          <strong>25<sup>$</sup></strong>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- slide three end -->\r\n");
      out.write("\r\n");
      out.write("    <!-- slide four start -->\r\n");
      out.write("    <div class=\"ls-slide ls-slide4\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 110,111,112,113;\">\r\n");
      out.write("\r\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide5/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"ls-l ls-title\" style=\"top: 35%; left: 60%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true; \r\n");
      out.write("      durationin: 750; \r\n");
      out.write("      durationout: 750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      rotatein: 90; \r\n");
      out.write("      rotateout: -90; \r\n");
      out.write("      scalein: .5; \r\n");
      out.write("      scaleout: .5; \r\n");
      out.write("      showuntil: 4000;\">\r\n");
      out.write("      The most<br>\r\n");
      out.write("      wanted bijouterie\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"ls-l ls-mini-text\" style=\"top: 70%; left: 60%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("      fade: true; \r\n");
      out.write("      fadeout: true;  \r\n");
      out.write("      durationout: 750; \r\n");
      out.write("      easingin: easeOutQuint; \r\n");
      out.write("      delayin: 300; \r\n");
      out.write("      scalein: .8; \r\n");
      out.write("      scaleout: .8; \r\n");
      out.write("      showuntil: 4000;\">\r\n");
      out.write("      <span>Lorem ipsum and</span>\r\n");
      out.write("      <a href=\"#\">Buy It Now!</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- slide four end -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- LayerSlider end -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END SLIDER -->\r\n");
      out.write("<!-- BEGIN SALE PRODUCT & NEW ARRIVALS -->\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("	<div class=\"row margin-bottom-40\">\r\n");
      out.write("	  <!-- BEGIN SALE PRODUCT -->\r\n");
      out.write("	  <div class=\"col-md-12 sale-product\">\r\n");
      out.write("	    <h2>New Arrivals</h2>\r\n");
      out.write("	    <div class=\"owl-carousel owl-carousel5\">\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	          <div class=\"sticker sticker-sale\"></div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress2</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model6.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model6.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress2</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	          <div class=\"product-item\">\r\n");
      out.write("	            <div class=\"pi-img-wrapper\">\r\n");
      out.write("	              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	              <div>\r\n");
      out.write("	                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	                <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	              </div>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <h3><a href=\"#\">Berry Lace Dress4</a></h3>\r\n");
      out.write("	            <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	            <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	            <div class=\"sticker sticker-new\"></div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model5.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model5.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress5</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress3</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model7.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model7.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress3</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <!-- END SALE PRODUCT -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- END SALE PRODUCT & NEW ARRIVALS -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- BEGIN SIDEBAR & CONTENT -->\r\n");
      out.write("	<div class=\"row margin-bottom-40 \">\r\n");
      out.write("	  <!-- BEGIN SIDEBAR -->\r\n");
      out.write("	  <div class=\"sidebar col-md-3 col-sm-4\">\r\n");
      out.write("	    <ul class=\"list-group margin-bottom-25 sidebar-menu\">\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Ladies</a></li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix dropdown\">\r\n");
      out.write("	        <a href=\"shop-product-list.html\">\r\n");
      out.write("	          <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("	          Mens\r\n");
      out.write("	          \r\n");
      out.write("	        </a>\r\n");
      out.write("	        <ul class=\"dropdown-menu\">\r\n");
      out.write("	          <li class=\"list-group-item dropdown clearfix\">\r\n");
      out.write("	            <a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Shoes </a>\r\n");
      out.write("	              <ul class=\"dropdown-menu\">\r\n");
      out.write("	                <li class=\"list-group-item dropdown clearfix\">\r\n");
      out.write("	                  <a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Classic </a>\r\n");
      out.write("	                  <ul class=\"dropdown-menu\">\r\n");
      out.write("	                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Classic 1</a></li>\r\n");
      out.write("	                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Classic 2</a></li>\r\n");
      out.write("	                  </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	                <li class=\"list-group-item dropdown clearfix\">\r\n");
      out.write("	                  <a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sport  </a>\r\n");
      out.write("	                  <ul class=\"dropdown-menu\">\r\n");
      out.write("	                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sport 1</a></li>\r\n");
      out.write("	                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sport 2</a></li>\r\n");
      out.write("	                  </ul>\r\n");
      out.write("	                </li>\r\n");
      out.write("	              </ul>\r\n");
      out.write("	          </li>\r\n");
      out.write("	          <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Trainers</a></li>\r\n");
      out.write("	          <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Jeans</a></li>\r\n");
      out.write("	          <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Chinos</a></li>\r\n");
      out.write("	          <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> T-Shirts</a></li>\r\n");
      out.write("	        </ul>\r\n");
      out.write("	      </li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Kids</a></li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Accessories</a></li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sports</a></li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Brands</a></li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Electronics</a></li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Home & Garden</a></li>\r\n");
      out.write("	      <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Custom Link</a></li>\r\n");
      out.write("	    </ul>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <!-- END SIDEBAR -->\r\n");
      out.write("	  <!-- BEGIN CONTENT -->\r\n");
      out.write("	  <div class=\"col-md-9 col-sm-8\">\r\n");
      out.write("	    <h2>Three items</h2>\r\n");
      out.write("	    <div class=\"owl-carousel owl-carousel3\">\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	          <div class=\"sticker sticker-new\"></div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress2</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress3</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress4</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	          <div class=\"sticker sticker-sale\"></div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress5</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress6</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <!-- END CONTENT -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- END SIDEBAR & CONTENT -->\r\n");
      out.write("	\r\n");
      out.write("	<!-- BEGIN TWO PRODUCTS & PROMO -->\r\n");
      out.write("	<div class=\"row margin-bottom-35 \">\r\n");
      out.write("	  <!-- BEGIN TWO PRODUCTS -->\r\n");
      out.write("	  <div class=\"col-md-6 two-items-bottom-items\">\r\n");
      out.write("	    <h2>Two items</h2>\r\n");
      out.write("	    <div class=\"owl-carousel owl-carousel2\">\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div>\r\n");
      out.write("	        <div class=\"product-item\">\r\n");
      out.write("	          <div class=\"pi-img-wrapper\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	            <div>\r\n");
      out.write("	              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("	              <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("	          <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("	          <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <!-- END TWO PRODUCTS -->\r\n");
      out.write("	  <!-- BEGIN PROMO -->\r\n");
      out.write("	  <div class=\"col-md-6 shop-index-carousel\">\r\n");
      out.write("	    <div class=\"content-slider\">\r\n");
      out.write("	      <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("	        <!-- Indicators -->\r\n");
      out.write("	        <ol class=\"carousel-indicators\">\r\n");
      out.write("	          <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("	          <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("	          <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("	        </ol>\r\n");
      out.write("	        <div class=\"carousel-inner\">\r\n");
      out.write("	          <div class=\"item active\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/index-sliders/slide1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <div class=\"item\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/index-sliders/slide2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <div class=\"item\">\r\n");
      out.write("	            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/index-sliders/slide3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("	          </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  <!-- END PROMO -->\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>        \r\n");
      out.write("<!-- END TWO PRODUCTS & PROMO -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
